# Generated by Django 2.0.13 on 2020-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20200430_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
