# Generated by Django 2.1.4 on 2021-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_auto_20210209_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='bankda_password',
            field=models.CharField(default='1111', max_length=16),
            preserve_default=False,
        ),
    ]
