# Generated by Django 2.1.4 on 2021-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_owner_bankda_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='bankda_password',
            field=models.CharField(max_length=10),
        ),
    ]
