# Generated by Django 2.1.4 on 2021-03-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_auto_20210217_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_stamp',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
