# Generated by Django 2.1.4 on 2021-08-17 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_auto_20210423_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='degree',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
